# GitHub Actions CI/CD Pipeline for Qwen3-VL
# This workflow builds, tests, and deploys the application

name: Build, Test, and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: qwen3-vl-cluster
  GKE_ZONE: us-central1-a
  IMAGE_NAME: qwen3-vl
  DEPLOYMENT_NAME: qwen3-vl

jobs:
  # Job 1: Run tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio httpx

    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      run: |
        pytest tests/ --cov=app --cov-report=xml --cov-report=html -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: htmlcov/

  # Job 2: Build and push Docker image
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || github.event_name == 'release'

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Google Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./examples/Dockerfile.production
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}

  # Job 3: Security scanning
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || github.event_name == 'release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

  # Job 4: Deploy to staging (develop branch)
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build, security-scan]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    environment:
      name: staging
      url: https://staging.qwen3-vl.example.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} \
          --zone ${{ env.GKE_ZONE }}

    - name: Deploy to Kubernetes (Staging)
      run: |
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
          ${{ env.IMAGE_NAME }}=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          -n qwen3-vl-staging

        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} \
          -n qwen3-vl-staging \
          --timeout=5m

    - name: Verify deployment
      run: |
        kubectl get services -n qwen3-vl-staging
        kubectl get pods -n qwen3-vl-staging

  # Job 5: Deploy to production (main branch)
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, security-scan]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: production
      url: https://qwen3-vl.example.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} \
          --zone ${{ env.GKE_ZONE }}

    - name: Deploy to Kubernetes (Production)
      run: |
        # Update deployment with new image
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
          ${{ env.IMAGE_NAME }}=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          -n qwen3-vl

        # Wait for rollout to complete
        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} \
          -n qwen3-vl \
          --timeout=10m

    - name: Verify deployment
      run: |
        kubectl get services -n qwen3-vl
        kubectl get pods -n qwen3-vl
        kubectl get ingress -n qwen3-vl

    - name: Run smoke tests
      run: |
        # Wait for service to be ready
        sleep 30

        # Get the service URL
        SERVICE_URL=$(kubectl get ingress qwen3-vl-ingress -n qwen3-vl -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

        # Health check
        curl -f http://$SERVICE_URL/health || exit 1

        echo "Deployment successful!"

  # Job 6: Deploy to Cloud Run (alternative serverless deployment)
  deploy-cloud-run:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: cloud-run
      url: https://qwen3-vl-run.example.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy qwen3-vl \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --gpu 1 \
          --gpu-type nvidia-l4 \
          --memory 16Gi \
          --cpu 4 \
          --timeout 300 \
          --concurrency 1 \
          --min-instances 0 \
          --max-instances 5 \
          --allow-unauthenticated \
          --port 8000

    - name: Get Cloud Run URL
      run: |
        SERVICE_URL=$(gcloud run services describe qwen3-vl \
          --platform managed \
          --region us-central1 \
          --format 'value(status.url)')
        echo "Service deployed to: $SERVICE_URL"

  # Job 7: Rollback on failure
  rollback:
    name: Rollback Deployment
    runs-on: ubuntu-latest
    needs: deploy-production
    if: failure()

    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} \
          --zone ${{ env.GKE_ZONE }}

    - name: Rollback deployment
      run: |
        kubectl rollout undo deployment/${{ env.DEPLOYMENT_NAME }} -n qwen3-vl
        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n qwen3-vl

    - name: Notify about rollback
      run: |
        echo "Deployment rolled back due to failure"
        # Add notification logic here (Slack, email, etc.)

  # Job 8: Notify on success
  notify-success:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: success()

    steps:
    - name: Send success notification
      run: |
        echo "Deployment successful!"
        # Add notification logic here (Slack, email, PagerDuty, etc.)
        # curl -X POST -H 'Content-type: application/json' \
        #   --data '{"text":"Qwen3-VL deployed successfully!"}' \
        #   ${{ secrets.SLACK_WEBHOOK_URL }}
